---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: web
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: aozturk12/hello:1.0
        ports:
        - containerPort: 8080
