apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: profile
  sessionAffinity: None
  type: LoadBalancer
