---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: web
spec:
  selector:
    matchLabels:
      app: profile
  replicas: 1
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: aozturk12/profile:1.0
        ports:
        - containerPort: 8080
