apiVersion: v1
kind: Service
metadata:
  name: trace
  namespace: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: trace
  sessionAffinity: None
  type: LoadBalancer

