apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sample-sm
    prometheus: kube-prometheus
  name: sample-sm
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: sampleapp
